### PR TITLE
Fixed linting destroyed editor

### LINKED ISSUE #153: Uncaught Error: This TextEditor has been destroyed
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.2.2

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:829

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:790:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/cursor.js:71:26)
    at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1432:35)
    at Function.fixString (/Users/egorkamenev/.atom/packages/linter-jscs/index.js:154:35)
    at /Users/egorkamenev/.atom/packages/linter-jscs/index.js:79:16
    at Function.module.exports.Emitter.simpleDispatch (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1060:27)
    at TextBuffer.module.exports.TextBuffer.save (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1030:19)
    at TextEditor.module.exports.TextEditor.save (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:602:26)
    at Pane.module.exports.Pane.saveItem (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:633:35)
    at atom-workspace.commandRegistry.add.core:save (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Users/egorkamenev/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:13.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:12.8.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -1:11.4.0 core:move-left (atom-text-editor.editor.is-focused)
  8x -1:10.7.0 core:select-right (atom-text-editor.editor.is-focused)
  3x -1:10 core:select-left (atom-text-editor.editor.is-focused)
     -0:40.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:24.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:23.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:22.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:14.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:14 core:save (atom-text-editor.editor.is-focused)
     -0:12.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.4.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai"
    ],
    "openEmptyEditorOnStart": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "linter-jshint"
    ]
  },
  "linter-jscs": {
    "displayAs": "jscs Error",
    "esnext": true,
    "fixOnSave": true,
    "onlyConfig": true,
    "configPath": ".jscs.json"
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.11.3
linter-jscs, v3.2.2
monokai, v0.18.0
seti-ui, v0.8.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by axit-rasmus**
Fixes #153 

This seems to address the issue with the destroyed editors. I have not done anything previously with atom plugins, please be rigorous in the review.

I have appropriated this solution from [here](https://github.com/gandm/language-babel/commit/b9a9c612740de4dc871c2f68d59388d3acadaf1d) where they appear to have fixed the same problem.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Why did you change the file permissions to executable?

File: src/linter-jscs.js [hunk 1]
```diff
@@ -90,19 +91,23 @@ export default class LinterJSCS {
...
+      const currentEditor = new CompositeDisposable;
+      this.textEditors.set(editor.id, currentEditor);
+      currentEditor.add(editor.getBuffer().onWillSave(() => {
         if (grammarScopes.indexOf(editor.getGrammar().scopeName) !== -1 || this.testFixOnSave) {
           // Exclude `excludeFiles` for fix on save
           const config = this.getConfig(editor.getPath());
-          const exclude = globule.isMatch(
-            config && config.excludeFiles, this.getFilePath(editor.getPath())
-          );
+          const exclude = globule.isMatch(config && config.excludeFiles, this.getFilePath(editor.getPath()));
```
Comment (Arcanemagus) [inline src/linter-jscs.js]: I'm not sure how this is passing the CI lint, but this line is past the maximum allowed length with this change.

**Comment by Arcanemagus** [comment]
This looks to be missing the [id checking](https://github.com/gandm/language-babel/commit/b9a9c612740de4dc871c2f68d59388d3acadaf1d#diff-2e1bb36917ff76ab7308da52bc968501R18) of the commit you are referencing, which seems to me to be a key part of ensuring we are acting on the right editor.

File: src/linter-jscs.js [hunk 2]
```diff
@@ -90,19 +91,23 @@ export default class LinterJSCS {
...
 
           if ((this.fixOnSave && !exclude) || this.testFixOnSave) {
             this.fixString(editor);
           }
         }
-      });
+      }));
+      return currentEditor.add(editor.onDidDestroy(() => {
```
Comment (Arcanemagus) [inline src/linter-jscs.js]: No need for a return statement here, the value isn't being used.

File: src/linter-jscs.js [hunk 3]
```diff
@@ -90,19 +91,23 @@ export default class LinterJSCS {
...
+        currentEditor.dispose();
+        return this.textEditors.delete(editor.id);
```
Comment (Arcanemagus) [inline src/linter-jscs.js]: Again, no need to return a value here.

**Comment by Arcanemagus** [comment]
That's what I see from looking at the code so far, thanks for taking the initiative here!

**Comment by axit-rasmus** [comment]
I didn't (purposely) change file permissions, maybe a side effect of something else. I hadn't even noticed.
Thanks for the feedback. I quickly fixed the issues you mentioned, but I'll have more time tomorrow.

File: src/linter-jscs.js [hunk 4]
```diff
@@ -105,7 +108,11 @@ export default class LinterJSCS {
             this.fixString(editor);
           }
         }
-      });
+      }));
+      currentEditor.add(editor.onDidDestroy(() => {
+        currentEditor.dispose();
```
Comment (Arcanemagus) [inline src/linter-jscs.js]: Should this be `editor.dispose()`? Or maybe `this.textEditors.get(editor.id).dispose()`?

File: src/linter-jscs.js [hunk 5]
```diff
@@ -105,7 +108,11 @@ export default class LinterJSCS {
             this.fixString(editor);
           }
         }
-      });
+      }));
+      currentEditor.add(editor.onDidDestroy(() => {
```
Comment (Arcanemagus) [inline src/linter-jscs.js]: Same comment as on the line below.

**Comment by Arcanemagus** [comment]
I'm not sure if those changes are necessary, it would just match the reference commit.

File: src/linter-jscs.js (hunk 4 above)
Comment (axit-rasmus) [inline src/linter-jscs.js]: What I gather from the docs and the referenced solution is that this `currentEditor` represents a group of event handlers, for the argument `editor`. So when the `onDidDestroy` happens we need to dispose this entire group.
Otherwise we'd probably have a memory leak in the Map, which is required as well.
I'll try to clarify this a bit

Comment (Arcanemagus) [inline src/linter-jscs.js]: I just wasn't sure if `currentEditor` referred to the correct editor when it would eventually be destroyed, since the referenced commit referred back to their equivalent of the Map, instead of using it directly.

**Comment by axit-rasmus** [comment]
I hope these changes make it a bit easier to digest. It should work fine, and does as far as I can tell.

File: src/linter-jscs.js (hunk 4 above)
Comment (axit-rasmus) [inline src/linter-jscs.js]: With `const` we can be sure of that. Maybe it wouldn't work the same in cofeescript, I seem to recall something about differing scoping rules.

**Comment by Arcanemagus** [comment]
LGTM, sorry for the delay I was pretty sick towards the end of last week :unamused:.

**Comment by Arcanemagus** [comment]
Published in v4.0.2, now that GitHub finally showed the commits here :stuck_out_tongue:.

**Comment by axit-rasmus** [comment]
No big deal at all, glad this is solved at last :smile:
