### PR TITLE
Added command to fix current file

### LINKED ISSUE #211: Fix file from command palette instead of on save
### Version
linter-jscs: 3.4.10
Atom: 1.6.2

### Issue
I was wondering if it was possible to fix the file from the command palette, rather than having to enable the fix file on save feature? I don't want to fix my file every time I press save, but would like to be able to do it from the command palette. 

Unfortunately I can't find any information on this. I tried the [jscs-fixer](https://atom.io/packages/jscs-fixer) package, but it causes a lot of errors and does not fix the file for me.

### PR DESCRIPTION
**Pull request by niekert**
This adds a command to the command palette to fix the current file

Fixes #211.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Edited your comment to make it so the related issue is automatically closed when this is merged, and to test whether the Audit log is working properly (It's not... filing a support request with GitHub :confused:).

File: src/linter-jscs.js [hunk 1]
```diff
@@ -97,6 +97,19 @@ export default class LinterJSCS {
         }
       });
     }));
+
+    this.subscriptions.add(atom.commands.add('atom-text-editor', {
+      'linter-jscs:fix-file': () => {
+        const textEditor = atom.workspace.getActiveTextEditor();
+
+        if (!textEditor || textEditor.isModified()) {
```
Comment (Arcanemagus) [inline src/linter-jscs.js]: Since `jscs` can fix a string the check as to whether it has been modified isn't necessary here and can be removed.

Also note that the message below should then be changed to something along the lines of "Invalid TextEditor received, aborting.". (Which will only trigger if there is a bug in Atom anyway...)

Comment (niekert) [inline src/linter-jscs.js]: Thanks for the feedback, wasn't aware of that! I just looked at the fix file command of the ESHint linter (I don't much experience with Atom). I'll add a new commit to fix this soon!

Comment (Arcanemagus) [inline src/linter-jscs.js]: Not a problem, the `eslint` fix only works on a file on disk, which is why the check is there for it :wink:.

Comment (niekert) [inline src/linter-jscs.js]: Makes sense! Fixed it in the new commit 😃

**Comment by Arcanemagus** [comment]
Sorry, one more thing: Can you add specs?

It should be something along the lines of [this block](https://github.com/AtomLinter/linter-jscs/blob/v3.4.10/spec/linter-jscs-spec.js#L151-L157) to open a file that will be fixed, triggering your command, then [running the linter](https://github.com/AtomLinter/linter-jscs/blob/v3.4.10/spec/linter-jscs-spec.js#L164-L166) and verifying there are no remaining messages.

To trigger the command I think you need to use [atom.commands.dispatch()](https://atom.io/docs/api/v1.6.2/CommandRegistry#instance-dispatch), but I'm unsure of what the DOM node to use as the target should be, the editor maybe? Unfortunately it looks like that is currently not being tested in `linter-eslint` so we can't use that as a reference.

**Comment by niekert** [comment]
Added the spec in the last commit. Passing the editorView as the target did the trick! Thanks for the guidance 😄

**Comment by Arcanemagus** [comment]
Awesome, thanks!

**Comment by Arcanemagus** [comment]
Nice, squash-commit still shows you as the author :grinning:.

**Comment by Arcanemagus** [comment]
Published in v3.5.0 :tada:
